### ISSUE TITLE
Calling private constructor

### ISSUE THREAD

**Issue by MarcelFadtke** [mikebrock/jboss-websockets#2]
Hello mikebrock,

I'd like to test your websocket example.
I read your README text and i noticed, that you calling the private constructor of "TextFrame":

 @Override
  protected void onReceivedFrame(WebSocket socket) throws IOException {
   [...]
        socket.writeFrame(new TextFrame("Hey, there!"));
      }
    }
  }

May you like to change it :)

Furthermore I'd like to ask you, if you have a working example by using your jboss-websockets?
I tried to integrate atmosphere framework and your jboss-websockets in jboss 7, but i didn't get it :(

**Comment by mikebrock** [comment]
There is actually a static factory method TextFrame.from() you use to create a new text frame. I have updated the README.
